basic_input.exe: basic_input.cpp 
	g++ basic_input.cpp -o basic_input.exe
basic_output.exe: basic_output.cpp 
	g++ basic_output.cpp -o basic_output.exe
error_finding.exe: error_finding.cpp 
	g++ error_finding.cpp -o error_finding.exe
clean:
	del *.o *.exe